<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_delete</name>
   <tag></tag>
   <elementGuidId>bc1e0174-e6c3-4489-95d3-ad04caf4108f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill-rule</name>
      <type>Main</type>
      <value>evenodd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>clip-rule</name>
      <type>Main</type>
      <value>evenodd</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-miterlimit</name>
      <type>Main</type>
      <value>1.414</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 32 32</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>preserveAspectRatio</name>
      <type>Main</type>
      <value>xMidYMid meet</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon__InlineSvg-sc-1oek49q-0 wLBhT</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>delete</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;style__Container-sc-1knjuu0-0 ctCOxz&quot;]/div[@class=&quot;style__ThreadContainer-sc-1knjuu0-3 cgzFBc&quot;]/main[@id=&quot;main&quot;]/div[@class=&quot;layout__SingleColumnGrid-sc-1v43im1-1 fIHtDT&quot;]/section[@class=&quot;layout__PrimaryColumn-sc-1v43im1-5 kQYRvL&quot;]/div[@class=&quot;style__Stretch-kw3szu-63 dUgTIg&quot;]/div[@class=&quot;style__MessagesWrapper-sc-1vl9d7j-0 cnOBDS&quot;]/div[@class=&quot;style__MessageGroupContainer-sc-1vl9d7j-1 eGWcNG&quot;]/div[@class=&quot;style__OuterMessageContainer-hbwp71-8 kdZQyy&quot;]/div[@class=&quot;style__InnerMessageContainer-hbwp71-9 ivJarz&quot;]/span[@class=&quot;style__ActionsContainer-hbwp71-3 gvHmHT&quot;]/ul[@class=&quot;style__Actions-hbwp71-4 eqNRQ&quot;]/li[@class=&quot;style__Action-hbwp71-5 iEmpdI&quot;]/div[@class=&quot;icon icon__SvgWrapper-sc-1oek49q-1 iKOKZk&quot;]/svg[@id=&quot;delete&quot;]</value>
   </webElementProperties>
</WebElementEntity>
